language: python

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

# command to install dependencies
install: 
  - make init
  - pip install codecov

# command to run tests
script: 
  - nosetests --with-coverage tests 

# command to create coverage report
before_install:
  pip install codecov
after_success:
  codecov